# Generated by Django 3.1.2 on 2020-12-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='contenido',
            field=models.TextField(),
        ),
    ]
