# Generated by Django 3.1.2 on 2020-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20201207_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madrealumno',
            name='alumno',
        ),
        migrations.AddField(
            model_name='madrealumno',
            name='alumno',
            field=models.ManyToManyField(related_name='madre_alumno', to='gestion.Alumno'),
        ),
        migrations.RemoveField(
            model_name='padrealumno',
            name='alumno',
        ),
        migrations.AddField(
            model_name='padrealumno',
            name='alumno',
            field=models.ManyToManyField(related_name='padre_alumno', to='gestion.Alumno'),
        ),
    ]
