# Generated by Django 3.1.2 on 2020-12-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20201207_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(to='gestion.Curso'),
        ),
    ]
