# Generated by Django 3.1.2 on 2020-12-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alumno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
