# Generated by Django 3.1.2 on 2020-12-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20201208_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pago_curso', to='gestion.curso'),
            preserve_default=False,
        ),
    ]
