# Generated by Django 3.1.4 on 2020-12-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_pago_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='Alumno',
            new_name='alumno',
        ),
    ]
